spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wcg
    password: wcg2019
    virtual-host: /
    publisher-confirms: true

server: 
  port: 8085